version: "3.8"

services:
  # PostgreSQL Database for development
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-nextstack_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nextstack_password}
      POSTGRES_DB: ${DB_NAME:-nextstack_dev}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/pgdata
      # Optional: Add init script if exists
      # - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - nextstack-dev-network

volumes:
  postgres_dev_data:
    driver: local

networks:
  nextstack-dev-network:
    name: nextstack-dev-network