version: "3.8"

services:
  # PostgreSQL Database for development
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-nextstack_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nextstack_password}
      POSTGRES_DB: ${DB_NAME:-nextstack_dev}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/pgdata
      # Optional: Add init script if exists
      # - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - nextstack-dev-network

  # MinIO Storage for development
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-nextstack_minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-nextstack_password}
    ports:
      - "${MINIO_PORT:-9000}:9000"       # S3 API
      - "${MINIO_CONSOLE_PORT:-9001}:9001" # Web Console
    volumes:
      - minio_dev_data:/data
    command: server /data --console-address ":9001"
    networks:
      - nextstack-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local
  minio_dev_data:
    driver: local

networks:
  nextstack-dev-network:
    name: nextstack-dev-network